INSERT INTO [dbo].[UpdateService] ([Code], [Catagory], [Name], [Price]) VALUES (N'', N'', N'', N'')
INSERT INTO [dbo].[UpdateService] ([Code], [Catagory], [Name], [Price]) VALUES (N'112', N'Manicure', N'Gel Manicure', N'789')
INSERT INTO [dbo].[UpdateService] ([Code], [Catagory], [Name], [Price]) VALUES (N'113', N'Facial', N'Anti Tan Facial', N'1860')
INSERT INTO [dbo].[UpdateService] ([Code], [Catagory], [Name], [Price]) VALUES (N'114', N' Facial', N'Hydra Facial', N'1140')
INSERT INTO [dbo].[UpdateService] ([Code], [Catagory], [Name], [Price]) VALUES (N'116', N'Hair Cut', N'Layer Cut', N'990')
INSERT INTO [dbo].[UpdateService] ([Code], [Catagory], [Name], [Price]) VALUES (N'117', N'Hair Cut', N'V Cut', N'670')
INSERT INTO [dbo].[UpdateService] ([Code], [Catagory], [Name], [Price]) VALUES (N'121', N'Make Up', N'Party Look', N'3450')
